[profile.default]
solc_version = "0.8.23"
evm_version = "shanghai"

via_ir = true

optimizer = true
optimizer_runs = 9_999_999

remappings = [
  "@solady=lib/solady/",
  "@forge=lib/forge-std/src/",
  "@nani=lib/accounts/src/"
]

[fmt]
line_length = 100

[rpc_endpoints]
main = "https://rpc.ankr.com/eth"